import type { Clue } from "./types";

/*
 * ============================================================================
 *  The clue booklet — transcribed from the printed game.
 * ============================================================================
 *  Source photos: /public/clues/booklet-clues-*.jpg (clues 1–320).
 *
 *  Every clue's `text` is transcribed verbatim from the booklet and has been
 *  hand-checked against the source photos (two independent passes plus a
 *  per-line review), so all clues are marked `verified: true`. Any clue listed
 *  in `UNCERTAIN` is treated as not-yet-verified; that set is currently empty.
 *
 *  Each clue links to the booklet photo that contains it via `clueImage(n)`,
 *  surfaced on the Ledger / verify page for spot-checking against the print.
 * ============================================================================
 */

export const TOTAL_CLUES = 320;

/**
 * Every clue's `text` is transcribed verbatim from the booklet and was
 * cross-checked against the photos in a second independent pass. No clues
 * remain flagged uncertain; `UNCERTAIN` is kept (empty) so future shaky
 * readings can be flagged again.
 */
const UNCERTAIN = new Set<number>([]);

/** Booklet text for clues 1–320, in order (index 0 = clue 1). */
const TEXT: string[] = [
  "Unless the motive was espionage, the Actress is guilty.",
  "One of the killers smoked a Cuban cigar.",
  "If the Fortuneteller is guilty, she had at least one accomplice.",
  "The Diplomat, Fortuneteller, Baroness, and Heiress were having a seance in the library from 6 o'clock until 7, and none of them could have committed the crime during that time.",
  "If the Fortuneteller is guilty, the motive was blackmail, espionage, or money; the Fortuneteller is righthanded.",
  "At least one of the women is guilty.",
  "If there were three or more killers, the motive was either blackmail, money, or revenge. The Doctor and the Cook can narrow down the time of death.",
  "There was just one killer.",
  "If the Fortuneteller is guilty, the motive was insanity or revenge; the Fortuneteller speaks French.",
  "From 7 o'clock on, only the Entrepreneur or Gambler could have committed the crime.",
  "If the Entrepreneur is guilty, the motive was not jealousy; the Entrepreneur cannot pick a lock.",
  "The victim, Abdul Jamal, collected art objects that have camels as subjects. He carried a cane with a camel's head carved on it, and owned several glass camel sculptures. His body was found in Second Class.",
  "The Baroness and Heiress are experts on coins.",
  "If the Entrepreneur is guilty, he acted alone.",
  "If the Count is guilty, the motive was blackmail or revenge.",
  "The only time the Gambler could have committed the crime was between 5 and 6 o'clock, unless he had at least one accomplice who could have done the evil deed at that time.",
  "The victim, Horst Hochstapler, was shot to death in First Class. You can eliminate five motives by searching Second Class, sending a telegram asking about the victim, and questioning the Actress or Heiress.",
  "If the Count is guilty, the motive was insanity or jealousy.",
  "If the Diplomat is guilty, the motive was not insanity or revenge.",
  "If the Diplomat is guilty, the motive was espionage or jealousy.",
  "If the murder weapon was a kitchen knife, then either the Entrepreneur, Gambler, or Heiress is guilty.",
  "The Gambler is an expert on jewels.",
  "At least one woman is guilty, and there were fewer than three killers.",
  "The motive could not have been espionage or jealousy.",
  "If the Actress is guilty, the motive was blackmail, jealousy, or revenge; the Actress is not an expert in exotic poisons.",
  "If the Baroness is guilty, the motive was blackmail or insanity; the Baroness speaks French.",
  "The Gambler could only have committed the crime before 6 o'clock.",
  "If the Fortuneteller or the Heiress is guilty, the motive was revenge.",
  "The murder took place after 6 o'clock.",
  "The murder took place between 5 and 7 o'clock.",
  "Either the Baroness or Gambler is guilty, but not both of them.",
  "If the murder took place between 6 and 7 o'clock, then the Gambler and Heiress must both be innocent.",
  "The motive was either blackmail or revenge.",
  "If the Fortuneteller is guilty, the motive was blackmail or revenge; the Fortuneteller is not an expert in either coins or jewels.",
  "The Actress could only have committed the crime between 6 and 8 o'clock.",
  "If you question the Actress and search Second Class, you still will not be able to eliminate espionage or insanity as possible motives.",
  "If the Heiress is guilty, the motive was blackmail, insanity, or jealousy; the Heiress is not an expert in exotic poisons.",
  "The victim was not killed with a glass camel.",
  "If the Baroness is guilty, the motive was espionage or revenge.",
  "The Actress and Heiress are guilty, but they had an accomplice.",
  "If the Heiress is guilty, the motive was espionage or insanity.",
  "All killers had same motive, and it was not insanity.",
  "If the Entrepreneur is guilty, the motive was not espionage.",
  "If the Heiress is guilty, the motive was blackmail or insanity.",
  "If you questioned the Baroness, don't bother talking to the Fortuneteller; but the Count has further information about which suspects are coin experts, and the Actress can tell you more about which are jewel experts.",
  "The victim died shortly before 6 o'clock.",
  "The murder could not have taken place before 6 o'clock.",
  "If the Actress is guilty, the motive was espionage or money.",
  "If the Count is guilty, the motive was espionage or insanity.",
  "The killer was recently in Madagascar.",
  "If you question the Count, Diplomat, Entrepreneur, and Gambler, you won't be able to get more information about their motives from sending telegrams about them—but the telegrams will tell you which ones speak French.",
  "If there were two or more killers, the motive was either blackmail or revenge.",
  "The Diplomat and Gambler are not both guilty, although one of them may be.",
  "The Entrepreneur is guilty.",
  "If the Heiress is guilty, the motive was blackmail or jealousy.",
  "The murder weapon was not a knitting needle.",
  "The motive had to be insanity, money, or revenge. The victim was an expert in both coins and jewels; he kept a list with him showing whatever he was carrying, and he had a nervous habit of checking and rechecking it to make sure that nothing was missing.",
  "Two different kinds of stab wounds on the victim indicate that at least one man and one woman are guilty, and were together while committing the crime.",
  "From 5 to 6, the Actress and Diplomat were busy with the Fortuneteller in the drawing room, having their palms read; none of the three of them could have committed the crime during that hour.",
  "If the Gambler is guilty, the motive was espionage or insanity.",
  "The victim was still alive at 6 o'clock.",
  "If the Actress, Baroness, Diplomat, or Fortuneteller is guilty, then the motive was either espionage, money, or revenge.",
  "If the Baroness is guilty, the motive was blackmail, insanity, or revenge; the Baroness is righthanded.",
  "If the motive was revenge, then at least one of the Actress, Baroness, or Entrepreneur is guilty, and may have had one or more accomplices.",
  "If either the Baroness or the Fortuneteller is guilty, the motive was either blackmail, insanity, or revenge.",
  "The motive could not have been espionage or jealousy.",
  "If the Entrepreneur is guilty, the motive was not blackmail or money.",
  "If the Baroness is guilty, the motive was blackmail, jealousy, or revenge; the Baroness is an expert in both coins and jewels.",
  "The motive was not revenge.",
  "The motive was insanity.",
  "If the motive was revenge, then the murder was premeditated, and the weapon could not have been the cane or glass camel.",
  "Both the Baroness and the Gambler speak French.",
  "Both questioning the Doctor and searching Second Class, where the murder occurred, will yield essentially the same information; and if you have this information, you don't have to bother searching the Drawing Room or Smoking Lounge Areas. The victim's last name was Doe, but only the Conductor knows whether his first name was spelled \"John\" or \"Jon.\"",
  "The murder weapon was not a knife.",
  "I heard a shot at 4:30.",
  "The victim was shot to death prior to 6 o'clock.",
  "I shot the victim at 7:30, but am not sure I killed him.",
  "If the Gambler is guilty, the motive was espionage or jealousy.",
  "If the Diplomat is guilty, the motive was espionage or revenge.",
  "All the killers were present at the scene of the crime when the murder took place; and at least one killer had to know how to pick a lock.",
  "If the Baroness is guilty, the motive was not insanity.",
  "Neither the Actress nor the Count is guilty.",
  "If the Diplomat, Entrepreneur, or Gambler is guilty, the motive was not jealousy.",
  "If the Count is guilty, the motive could not have been revenge.",
  "There was more than one killer, and the motive was not blackmail.",
  "The murder could not have taken place after 7 o'clock.",
  "From 5 until 6 o'clock, all the female suspects were in the drawing room; the Fortuneteller was predicting the others' futures.",
  "The motive was not insanity.",
  "There was only one killer.",
  "If the Entrepreneur is guilty, the motive was espionage or insanity; the Entrepreneur is not an expert in either coins or jewels.",
  "The murder could not have taken place between 5 and 6 o'clock.",
  "If the Heiress is guilty, the motive was not money.",
  "The victim was killed in his berth between 6 and 8 o'clock; he was not poisoned, but died from being hit over the head with one of the three objects found near the body: either the glass camel, the cane with a camel's head, or the gun. Searching Second Class will rule out one of these objects.",
  "The Actress and Heiress will tell you exactly the same thing, which eliminates two motives.",
  "Among the suspects, at least three of the women are not experts in exotic poisons.",
  "If the Gambler is guilty, the motive was blackmail, insanity, or money; the Gambler is righthanded.",
  "The victim, George Gigolo, was shot to death. If you search First and Second Class and question the Valet, you will have enough information to eliminate two motives.",
  "If the murder weapon was a sword, then either the Baroness, Count, Diplomat, or Fortuneteller is guilty.",
  "If the Actress is guilty, the motive was not blackmail or revenge.",
  "Anyone who was not in the drawing room between 6 and 7 o'clock is innocent.",
  "None of the female suspects is ambidextrous; one is lefthanded, three are righthanded.",
  "If the Baroness is guilty, the motive was blackmail or jealousy.",
  "If the motive was either blackmail or insanity, then at least one of the Baroness, Count, and Gambler is guilty.",
  "If the murder took place after 7 o'clock, then the Baroness and Count must both be innocent.",
  "If the Heiress is guilty, the motive was money or revenge; the Heiress speaks French.",
  "From 6 o'clock until 8, the Baroness and Count were in the dining room.",
  "If the Fortuneteller is guilty, the motive was not money; the Fortuneteller cannot pick a lock.",
  "Neither the Fortuneteller nor the Gambler could have committed the murder between 5 and 6 o'clock.",
  "If the Entrepreneur is guilty, the motive was espionage, insanity, or money; the Entrepreneur is an expert in exotic poisons.",
  "If the Entrepreneur is guilty, the motive was not insanity.",
  "The Actress could not have committed the crime after 7 o'clock.",
  "No one entered the victim's berth after 7 o'clock; if he died then, he had to have been poisoned.",
  "If the Diplomat is guilty, the motive was blackmail or jealousy.",
  "Either the Actress or Diplomat is guilty, but not both of them.",
  "The motive was not insanity, jealousy, or revenge.",
  "If the Entrepreneur is guilty, the motive was espionage, money, or revenge; the Entrepreneur is righthanded.",
  "If the Fortuneteller is guilty, the motive was not insanity or money.",
  "The Waiter, Porter, and Valet know among themselves which suspects can speak French.",
  "If the Actress is guilty, the motive was insanity or money.",
  "The Count, Entrepreneur, and Gambler were in the dining room from 4 o'clock until 5, and could not have committed the crime during that hour. The Baroness and Heiress have an alibi from 5 to 7, when they dined together.",
  "If the murder weapon was a knife, then the Baroness and Count must both be innocent.",
  "The Actress, Baroness, Count, and Gambler all were in Spain recently. So was the victim, Don de Dondon, who was found dead in the library.",
  "If the Baroness is guilty, the motive was not revenge; the Baroness cannot pick a lock.",
  "If the Fortuneteller is guilty, the motive was insanity or jealousy.",
  "Both the Actress and the Baron speak Serbo-Croatian, but only the Actress will admit it.",
  "A close examination of scuff marks on the floor indicates that at least one man and one woman are guilty, and were together while committing the crime.",
  "If either the Count or Gambler is guilty, the motive was money.",
  "From 6 o'clock until 7, the Count, Diplomat, and Gambler were all in the dining room.",
  "The murder weapon was either a knife, an icepick, or a knitting needle.",
  "If the Count is guilty, the motive was insanity or jealousy; the Count is an expert in coins but not jewels.",
  "If the Fortuneteller is guilty, the motive was insanity or money.",
  "The victim, Penelope Pennypincher, was strangled with a rope. If you search Second Class, it will be a waste of time to question the Doctor.",
  "The Porter can pinpoint the number of killers.",
  "What the Actress says about the Count is also true of the Entrepreneur.",
  "The only motives I would ever have for murder are espionage or jealousy.",
  "None of the killers is an occupant of either berth 2 or berth 4.",
  "If the Heiress is guilty, the motive was espionage, jealousy, or money; the Heiress is lefthanded.",
  "I heard a gunshot at 7:30; and when I went to investigate, I saw the Count running away from the victim's berth.",
  "If the Heiress is guilty, the motive was not espionage or jealousy.",
  "If the Gambler is guilty, the motive was not espionage; the Gambler knows how to pick a lock.",
  "The Cook knows a lot about coins; the Porter knows a lot about jewels. The victim's name was Walter de Faulter. His body was found in Second Class.",
  "If the Count is guilty, the motive was espionage, jealousy, or money; the Count is an expert in exotic poisons.",
  "If the murder occurred between 5 and 7 o'clock, then at least one of the following suspects—the Actress, Entrepreneur, Fortuneteller, or Heiress—must have done it.",
  "If the Diplomat is guilty, the motive was espionage or money; the Diplomat, oddly enough for someone in his profession, does not speak French.",
  "None of the men are experts in coins.",
  "The Heiress was in the drawing room from 6 o'clock until 8. The Actress was there from 7 until 8.",
  "The motive could not have been blackmail, insanity, or jealousy.",
  "If there were fewer than 3 killers, then the Actress, Gambler, and Heiress are all innocent.",
  "The murder must have occurred either between 5 and 6 or between 7 and 8; at other times, a crewman was in the corridor outside the victim's berth. Neither the Actress nor the Baroness has ever owned or worn red shoes.",
  "The information you get from the Actress, Gambler, and Entrepreneur together is the same as you can get from questioning both the Porter and the Waiter. The victim's first name was spelled \"John.\"",
  "If the murder took place before 5 o'clock then the Count, Entrepreneur, and Heiress must all be innocent.",
  "If the Gambler is guilty, the motive was blackmail or money; the Gambler is an expert in both coins and jewels.",
  "If the Actress is guilty, the motive was espionage or revenge.",
  "If the Actress committed the crime before 5 o'clock, then she must have had the Gambler as an accomplice.",
  "There was just one killer, and the killer spoke French; the Conductor and I overheard part of a conversation between the killer and victim, but I couldn't be sure whether the killer was a man or a woman.",
  "One of the four men is guilty; the other three men are innocent.",
  "The motive was not espionage or insanity; and unless the killer was a woman, the motive was not revenge.",
  "If the Heiress is guilty, the motive was money or revenge.",
  "If the Count is guilty, the motive was espionage, insanity, or jealousy; the Count is righthanded.",
  "The Count is guilty. From 4 o'clock until 7, the Fortuneteller and three other suspects held a seance in the library.",
  "At least one of the men is guilty.",
  "The motive was not blackmail or jealousy.",
  "The motive was not espionage, insanity, or jealousy.",
  "If the Baroness, Count, Entrepreneur, or Gambler is guilty, then the motive was either blackmail, espionage, or revenge.",
  "If the Gambler is guilty, the motive was espionage, insanity, or jealousy; the Gambler is an expert in exotic poisons.",
  "If the Gambler is innocent, then so is the Fortuneteller.",
  "If the Baroness is guilty, she had at least one accomplice.",
  "Blackmail was not the motive.",
  "If insanity was the motive, the Diplomat alone must be guilty.",
  "The person staying in berth 3 is guilty; the Actress is innocent.",
  "The victim, D.V. Uss, could not have been killed after 7 o'clock. Now, if you question the Conductor, you will have enough information to realize that out of questioning the Waiter and searching the Dining, Drawing Room, and Smoking Lounge Areas, only one source of information will prove useful.",
  "The only time the Diplomat or Fortuneteller could have committed the crime was between 5 and 6 o'clock; at other times, they were in the dining car.",
  "If the murder took place before 6 o'clock, then the Count, Fortuneteller, Gambler, and Heiress must all be innocent; until then, they were all together in a fortunetelling session in the drawing room.",
  "Among the suspects, exactly two men and two women are experts on coins.",
  "If the Entrepreneur is guilty, the motive was espionage or revenge.",
  "If the Count is guilty, the motive was espionage or insanity.",
  "Berths 4 and 5 are unoccupied this trip.",
  "If the murder took place between 6 and 7 o'clock, then the Count, Diplomat, and Gambler must all be innocent.",
  "If the Entrepreneur is guilty, the motive was insanity or jealousy.",
  "The motive was not money.",
  "The Count could only have committed the crime before 6 o'clock.",
  "From 6 until 7, the Actress, Entrepreneur, Fortuneteller, and Gambler were in the dining room.",
  "If the Actress is guilty, the motive was jealousy or revenge; the Actress is an expert in jewels but not coins.",
  "The four women are staying in berths 1, 2, and 6; the four men are staying in berths 3, 4, and 5.",
  "If the Baroness and Heiress are both guilty, then the motive is not insanity or revenge.",
  "The only motives I would ever have for murder are jealousy or money.",
  "There was just one killer.",
  "The murder weapon was not a gun, and there was only one killer.",
  "If the Baroness is guilty, the motive was blackmail or insanity.",
  "If the victim was John Doe, the motive could not have been jealousy or revenge. If the victim was Jon Doe, the motive could not have been espionage or revenge.",
  "From 4 until 5, the Baroness, Count, Diplomat, and Heiress were in the dining room.",
  "If the Count is guilty, the motive was not blackmail; the Count cannot pick a lock.",
  "One killer was a woman occupying berth 1 or 2.",
  "If the Baroness is guilty, the motive was insanity or money.",
  "If the Entrepreneur is guilty, the motive was blackmail or revenge.",
  "The killer had to know that the victim ate a special diet; but any of the suspects could have known this, since it was discussed aloud earlier in the dining room. The killer had to either poison the victim's food in the kitchen between 4 and 5 o'clock or in the dining room between 5 and 6, while the victim was eating.",
  "The victim's name was Claude Fraud. If you question the Cook, the Valet, and the Waiter, you'll realize that at most one of them has useful information.",
  "The Fortuneteller could not have committed the crime between 4 and 5 or between 6 and 7, when she was in the dining room.",
  "From the angles of the stab wounds, either the killer had to be ambidextrous, or there were at least two killers, one of whom was lefthanded and one of whom was righthanded; the murder occurred sometime between 5 o'clock and 7 in the victim's Second Class berth.",
  "The killer walks with a limp.",
  "Unless the murder took place after 7 o'clock, the Entrepreneur could not have done it.",
  "If the Diplomat is guilty, the motive was espionage, insanity, or jealousy; the Diplomat is an expert in exotic poisons.",
  "At least one man and one woman are guilty.",
  "Neither the Actress nor the Count could have committed the murder earlier than 5 o'clock.",
  "The Diplomat would not have committed murder unless the Fortuneteller helped him. The Fortuneteller can give me a partial alibi.",
  "The murder had to take place either before 5 o'clock or after 7.",
  "The Entrepreneur and Gambler are sharing berth 4; the Actress and Fortuneteller are sharing berth 6.",
  "If the Count is guilty, the motive was blackmail, jealousy, or revenge.",
  "The Diplomat could only have committed the crime before 6 o'clock.",
  "If the Actress is guilty, the motive was blackmail, insanity, or jealousy; the Actress is righthanded.",
  "The Baroness knows three suspects who know very little about either coins or jewels. The Actress and Count know something about which suspects are jewel or coin experts.",
  "Both the Diplomat and the Fortuneteller are innocent.",
  "If the Actress is guilty, then so is either the Baroness or Heiress, or both.",
  "The motive was not espionage or insanity.",
  "If the Baroness is guilty, the motive was not jealousy or money.",
  "If the Entrepreneur is guilty, the motive was blackmail or espionage.",
  "If the Heiress is guilty, the motive was not espionage, jealousy, or revenge; the Heiress knows how to pick a lock.",
  "If the Heiress is guilty, the motive was espionage or money; the Heiress is an expert in both coins and jewels.",
  "The Heiress speaks French; the Count and the Diplomat do not.",
  "The victim had dined with the killer in Paris.",
  "If the Gambler is guilty, the motive was money or revenge.",
  "If the murder weapon was an icepick, neither the Count nor the Gambler is guilty. The Fortuneteller knows how to determine the murder weapon.",
  "The victim was already dead before he was shot.",
  "The list of coins the victim was carrying indicates that the killer took only the very best of the coins, and so must have been an expert on coins.",
  "A Spanish coin newly minted, is found on a corner of the kitchen floor.",
  "The victim was already dead when he was stabbed.",
  "The Count, the Diplomat, and the Gambler, whether acting alone or together, could only have committed the crime before 7 o'clock; after that, they were all in the dining room.",
  "From 5 o'clock until 6, only the Diplomat could have committed the crime.",
  "If the Count and Gambler are both guilty, then the motive is not blackmail or espionage. The Conductor can give me an alibi from 6 o'clock until 7.",
  "If the Entrepreneur is guilty, the motive was blackmail or espionage; the Entrepreneur does not speak French.",
  "If the Diplomat is guilty, the motive was espionage, insanity, or money; the Diplomat is not an expert in either coins or jewels.",
  "If the motive was blackmail or revenge, then either the Baroness or Count (or both) are guilty.",
  "If the Fortuneteller is guilty, the motive was blackmail, money, or revenge; the Fortuneteller is not an expert in exotic poisons.",
  "The victim was killed between 4 o'clock and 7 o'clock, but not between 5 and 6. The Diplomat can give the Entrepreneur an alibi.",
  "The Valet and Porter are collaborating on a mystery novel called \"The Lefthanded Killer,\" and they always notice what passengers are lefthanded and what ones are righthanded.",
  "The Baroness could only have committed the crime after 6 o'clock.",
  "If the Diplomat is guilty, the motive was not blackmail, insanity, or money; the Diplomat cannot pick a lock.",
  "The Diplomat, Entrepreneur, and Fortuneteller are not experts in either coins or jewels.",
  "If the Fortuneteller is guilty, the motive was blackmail or money.",
  "The Entrepreneur is not a spy, and could not have killed anyone for the reason of espionage.",
  "The only motives I would ever have for murder are blackmail or espionage.",
  "If the victim's food was poisoned before 5 o'clock, then the Baroness, Diplomat, Fortuneteller, and Heiress must all be innocent.",
  "The victim was still alive at 6 o'clock.",
  "If the murder took place after 6 o'clock, then the Baroness, Diplomat, Entrepreneur, and Heiress must all be innocent.",
  "If the Actress is guilty, the motive was insanity or money.",
  "The Heiress occupies berth 1, and the Entrepreneur occupies berth 4.",
  "From 7 until 8, all the male suspects were in the smoking lounge.",
  "The motive was not espionage or money.",
  "The Heiress could only have committed the crime between 6 and 7 o'clock.",
  "The victim was shot in the smoking lounge.",
  "At least two men are guilty, as well as a woman who was wearing red shoes.",
  "The Fortuneteller is innocent.",
  "The motive was not espionage.",
  "The Valet and the Doctor will tell you the same thing about the time of death, but the Doctor can also tell you whether or not the victim was poisoned.",
  "Between 5 and 7 o'clock, the Actress, Baroness, Diplomat, and Entrepreneur all were in the dining room.",
  "If the Diplomat is guilty, the motive was blackmail, money, or revenge; the Diplomat is lefthanded.",
  "The murder could not have occurred after 7 o'clock.",
  "Of the Fortuneteller and Heiress, at least one is innocent.",
  "The motive was either blackmail, espionage, or insanity.",
  "Only the Diplomat would have killed because of insanity; and if he is guilty, insanity was his motive.",
  "If the Diplomat is guilty, the motive was not espionage or money.",
  "The Heiress is innocent.",
  "If the Count is guilty, the motive was espionage or jealousy; the Count does not speak French.",
  "If the Heiress is guilty, then so is the Actress.",
  "If the Gambler is guilty, the motive was money or revenge.",
  "The motive was not blackmail or jealousy.",
  "If the Heiress is guilty, the motive was espionage or money.",
  "None of the male suspects is ambidextrous; one is lefthanded, three are righthanded.",
  "The killer took some coins and jewels (either because it was robbery—i.e., the motive was money—or because he or she wanted it to look that way) but left other coins and jewels behind, in the open. There was only one killer.",
  "If the Count is innocent, then so are the Fortuneteller and Gambler.",
  "Among the suspects, at least three of the men are experts in exotic poisons.",
  "The killer was a woman who could speak French; she had no accomplices.",
  "If the Diplomat, Entrepreneur, Fortuneteller, or Gambler is guilty, then the motive was either espionage, jealousy, or money.",
  "If the Actress is guilty, the motive was not insanity; the Actress cannot pick a lock.",
  "Unless the victim was a spy, the motive was not espionage.",
  "If the Fortuneteller is guilty, the motive was insanity or revenge.",
  "From 5 o'clock until 6, the Count, Entrepreneur, and Gambler were in the dining room; and the Actress, Baroness, and Diplomat were in the dining room from 6 until 7.",
  "The murder could not have occurred between 6 and 7 o'clock.",
  "The Actress, Baroness, Count, and Entrepreneur were in the dining room from 4 o'clock until 6, and could not have committed the crime during that time.",
  "Searching First and Second Class is likely to yield important information.",
  "If the Gambler is guilty, the motive was jealousy or money; the Gambler speaks French.",
  "If the food was poisoned between 5 and 6 o'clock, then the Baroness, Count, Entrepreneur, and Heiress must all be innocent.",
  "By questioning the Actress and searching the Kitchen Area and Second Class, you will pinpoint the murder weapon.",
  "The motive could not have been espionage or money.",
  "If the murder weapon was a pair of scissors, then either the Baroness, Count, or Diplomat is guilty.",
  "Among the suspects, exactly three women and one man are experts on jewels.",
  "The motive was not blackmail.",
  "If the Entrepreneur and Fortuneteller are both guilty, then the motive was not jealousy or money.",
  "If the Actress is guilty, the motive was blackmail or insanity; the Actress does not speak French.",
  "If the motive was either espionage or insanity, the Gambler is guilty.",
  "At least one man is guilty.",
  "The motive was not blackmail, insanity, or money.",
  "If the Baroness, Count, Gambler, or Heiress is guilty, then the motive was either espionage, insanity, or revenge.",
  "The occupant of berth 5 is the Count; the Entrepreneur occupies berth 4.",
  "The motive was not blackmail, jealousy, or revenge.",
  "If the Baroness is guilty, the motive was blackmail, money, or revenge; the Baroness is not an expert in exotic poisons.",
  "If the weapon was a cane, only one of the male suspects would have had the strength to make the fatal blow.",
  "The only motives I would ever have for murder are espionage or money.",
  "I was with the victim when he was killed, but someone knocked me out from behind.",
  "If the Diplomat is guilty, the murder weapon was a dagger.",
  "The victim, Selma Zealot, was shot in the corridor of the Sleeping Car. The Conductor, Porter, and Valet know about who's staying in what berths; after you question them, the Waiter may be helpful. Suspects were not necessarily in their own berths when the game started.",
  "The motive was not money or jealousy.",
  "The list of jewels the victim was carrying indicates that the killer took only the very best of the jewels, and so must have been an expert on jewels.",
  "If the murder took place after 7 o'clock, the Actress could not have done it.",
  "Searching both First Class and the Smoking Lounge Area will pinpoint the time where the murder occurred. The motive was not blackmail.",
  "The cause of death was an exotic poison, which must have been mixed with some food the victim ate; the killer—or at least one of the killers, if there were more than one—had to be an expert in exotic poisons to use it.",
  "From 5 o'clock until 6, the Baroness, Diplomat, and Gambler were all in the dining room.",
  "The Gambler and Heiress are both guilty.",
  "The Heiress could have committed the crime anytime except from 6 to 7 o'clock, when she was in the dining room.",
  "If the Diplomat is guilty, the motive was espionage or revenge.",
  "The motive was not jealousy or revenge.",
  "When the victim ate dinner between 5 and 6 o'clock, the Diplomat, Entrepreneur, Fortuneteller, and Gambler were the only suspects present in the dining room; one of them could have poisoned the food when the victim went to the wash room for a few minutes.",
  "The Baroness and Entrepreneur are not both guilty, but one of them may be.",
  "The motive was not money or revenge.",
  "At least one killer knows how to pick a lock.",
  "The Entrepreneur is innocent.",
  "If the victim was shot, it must have happened after 5 o'clock; otherwise, I would have heard the shot. There was just one killer.",
  "The victim was stabbed to death in First Class between 5 and 7 o'clock, with either a kitchen knife or a sword. He was also shot, after he was already dead.",
  "The Fortuneteller speaks French; the Actress and Entrepreneur do not.",
  "Every berth is occupied by either one or two suspects.",
];

if (TEXT.length !== TOTAL_CLUES) {
  throw new Error(`Expected ${TOTAL_CLUES} clues, got ${TEXT.length}`);
}

export const CLUES: Clue[] = TEXT.map((text, i) => {
  const n = i + 1;
  const uncertain = UNCERTAIN.has(n);
  return {
    n,
    text,
    // Verified once hand-checked against the booklet — i.e. everything that
    // is not still flagged uncertain.
    verified: !uncertain,
    uncertain: uncertain || undefined,
  };
});

/** Get a clue by its number (1-based), or undefined if out of range. */
export function clueByNumber(n: number): Clue | undefined {
  return CLUES[n - 1];
}

/**
 * Source-photo ranges for the booklet: [firstClue, lastClue, filename] under
 * /public/clues. Used to link each clue back to the page it was transcribed
 * from.
 */
const PHOTO_RANGES: [number, number, string][] = [
  [1, 26, "booklet-clues-001-026.jpg"],
  [27, 57, "booklet-clues-027-057.jpg"],
  [58, 85, "booklet-clues-058-085.jpg"],
  [86, 110, "booklet-clues-086-110.jpg"],
  [111, 138, "booklet-clues-111-138.jpg"],
  [139, 162, "booklet-clues-139-162.jpg"],
  [163, 190, "booklet-clues-163-190.jpg"],
  [191, 215, "booklet-clues-191-215.jpg"],
  [216, 241, "booklet-clues-216-241.jpg"],
  [242, 271, "booklet-clues-242-271.jpg"],
  [272, 299, "booklet-clues-272-299.jpg"],
  [300, 320, "booklet-clues-300-320.jpg"],
];

/** Path (under /public) to the booklet photo that contains clue `n`. */
export function clueImage(n: number): string | undefined {
  const range = PHOTO_RANGES.find(([lo, hi]) => n >= lo && n <= hi);
  return range ? `/clues/${range[2]}` : undefined;
}

/** Path (under /public) to the photo of the clue-numbers grid. */
export const GRID_IMAGE = "/clues/clue-numbers-grid.jpg";
